stages:
  - build

variables:
  UNITY_PATH: D:/Unity/Editor/2021.3.24f1/Editor/Unity.exe  # Unity编辑器路径
  PROJECT_PATH: D:/UnityProject/cicd-test  # Unity项目路径
  BUILD_PATH: D:/BuildTest/BuildByCommand  # 构建输出路径
  LOG_PATH: D:/BuildTest/BuildByCommandLog.txt  # 构建日志路径

# WebGL 构建任务
build_webgl:
  stage: build
  script:
    - echo "Checking UNITY_PATH: $UNITY_PATH"
    - echo "Checking BUILD_PATH: $BUILD_PATH"
    - ls -R $BUILD_PATH  # 列出构建路径的内容，确认是否有文件
    - "$UNITY_PATH" -batchmode -quit -projectPath "$PROJECT_PATH" -executeMethod WebGLTool.WebGLBuildScript.BuildProject -logFile "$LOG_PATH"
    - ls -R $BUILD_PATH  # 构建后再次列出，确保文件生成
    - tail -n 100 $LOG_PATH  # 查看最后100行构建日志，检查是否有错误
  artifacts:
    paths:
      - $BUILD_PATH  # 上传构建产物
  only:
    - main  # 只在 main 分支上触发构建